Museum Landing
mate-academy/Museum pull request #249
Opened 2023-02-20 21:15 UTC by Dmytro-Tymchenko

[DEMO LINK](https://Dmytro-Tymchenko.github.io/Museum/)

2023-02-21 09:40 UTC, OlEzhA0 requested changes
check your btn
<img width="320" alt="Screenshot 2023-02-21 at 11 39 42 AM" src="https://user-images.githubusercontent.com/60295799/220307411-5ac397d9-1769-404a-aafe-10b845c04c8f.png">


Good start!

2023-02-24 08:53 UTC, OlEzhA0 requested changes
hey! don't use png for small icons because it's blurs on large screens
<img width="168" alt="Screenshot 2023-02-24 at 10 51 42 AM" src="https://user-images.githubusercontent.com/60295799/221134594-f7fe2e16-9765-4256-9f68-4e10258681f9.png">

tablet screen
<img width="910" alt="Screenshot 2023-02-24 at 10 53 17 AM" src="https://user-images.githubusercontent.com/60295799/221134955-709671e6-38d2-4447-86cb-1f14d6f5e8d8.png">

check it pls)
<img width="381" alt="Screenshot 2023-02-24 at 10 53 42 AM" src="https://user-images.githubusercontent.com/60295799/221135051-855ba044-143f-4e4b-93ef-4a34c91e5597.png">

2023-02-26 12:13 UTC, VitaliyBondarenko1982 requested changes
Good job.
Check a couple moments
- On form submitting you need to use [preventDefault](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) to stop the update page and [reset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset) form
- after autocomplete the form, change the default styles. Read more about [changing autocomplete styles](https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/)

2023-02-27 15:25 UTC, Viktor-Kost requested changes
Hi!)

Found some moment you need to fix: 

1) remove page scroll when menu is opened
2) add an arrow to "купити" button 
![Screenshot 2023-02-27 at 17 20 47](https://user-images.githubusercontent.com/117587463/221604189-5f186096-27f5-4006-ba37-4da0a60c3966.png)

3) add an anchor link to "події"
![Screenshot 2023-02-27 at 17 21 23](https://user-images.githubusercontent.com/117587463/221604338-6192b8ae-b488-48ac-a0b2-cc8cf0c3ed6a.png)

4) remove basic blue hover effect and add your custom one
![Screenshot 2023-02-27 at 17 21 58](https://user-images.githubusercontent.com/117587463/221604500-39d8f547-ed79-48b5-b514-8905c0f63a61.png)

5) remove opening a new tab, when I click at phone number. New tab is only for that cases when you lead your user somewhere

6) add anchor links to all sections from this list
![Screenshot 2023-02-27 at 17 24 09](https://user-images.githubusercontent.com/117587463/221605114-7899f32c-1feb-464d-8c46-3f54088de7e7.png)

7) add correct links to social links
![Screenshot 2023-02-27 at 17 24 57](https://user-images.githubusercontent.com/117587463/221605297-ef0376ca-6da6-47c6-a14d-ce4d653dd453.png)

2023-02-27 18:00 UTC, etojeDenys approved these changes
LGTM

2025-08-08 08:25 UTC, closed without merging