Can you give me some feedback? I'm not sure, that I do correct
mate-academy/Museum pull request #254
Opened 2023-02-26 11:15 UTC by Vo7kov

https://vo7kov.github.io/Museum/

2023-02-26 11:48 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/

2023-02-26 18:25 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/

2023-02-26 18:34 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/

2023-02-27 10:49 UTC, VitaliyBondarenko1982 approved these changes
Good start.
Waiting more sections.
Looks like 
margin: 0 auto redundant.
and not reset margins and paddings in *
![Screenshot from 2023-02-27 12-47-42](https://user-images.githubusercontent.com/33029864/221544200-15430ecb-6f76-401a-a54b-ed9d2993fa89.png)

2023-02-27 10:53 UTC, VitaliyBondarenko1982 requested changes
Good start.
Waiting more sections.
Check horizontal margins.
![Screenshot from 2023-02-27 12-53-04](https://user-images.githubusercontent.com/33029864/221545020-de2c0f86-5c24-4b45-90d9-db391b70ab65.png)

2023-02-27 21:06 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/ - can you help me with menu on 768px? I don't know, what to do

2023-02-28 08:07 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/ - can you help me with menu on 768px? I don't know, what to do

2023-02-28 08:42 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/ - can you help me with menu on 768px? I don't know, what to do

2023-02-28 10:31 UTC, IvanFesenko requested changes
Ask you question in fe_chat. It's pretty hard to undertand your problem and make discussion here

2023-02-28 15:16 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/ - I add menu, but I dont know how to implement the dark bg when menu is open. I commented my solution in menu.scss, but it work only, when I remove translate from ::after and .menu. I'll ask for solution at qa

2023-03-01 08:25 UTC, vlad-demchuk requested changes
something wrong is here, check the mockup
if you have any questions, just feel free to ask in `fe_chat`
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/102411130/222084179-ed5123ce-962b-4ff9-9a40-c1393d84afaf.png">

2023-03-05 22:48 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/

2023-03-06 08:43 UTC, OlEzhA0 requested changes
waiting for footer section

when I sent form, it's redirected me to 405

check this bug pls
<img width="1792" alt="Screenshot 2023-03-06 at 10 43 11 AM" src="https://user-images.githubusercontent.com/60295799/223060058-956adfde-b9a9-4f9d-a69d-117246ab9eb1.png">

2023-03-06 09:32 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/

2023-03-06 09:35 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/

2023-03-06 09:40 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/

2023-03-06 10:31 UTC, VitaliyBondarenko1982 requested changes
Form looks good.
Waiting for footer section.

2023-03-06 22:34 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/ - don't approve it, slider section remains

2023-03-06 22:52 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/ - don't approve it, slider section remains

2023-03-07 09:17 UTC, OlEzhA0 requested changes
still not fixed
https://user-images.githubusercontent.com/60295799/223377664-308a973d-10b8-455c-bd57-ffbd93af73b4.mov

2023-03-07 10:04 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/

2023-03-07 10:38 UTC, IvanFesenko requested changes
Add links to this icons
![2023-03-07_12h32_32](https://user-images.githubusercontent.com/61904995/223397096-4be69000-2340-4a28-b956-7ceebfc4e547.png)
Waiting gallery section

2023-03-10 09:35 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/

2023-03-10 09:42 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/

2023-03-13 15:57 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/

2023-03-13 17:57 UTC, Viktor-Kost requested changes
Hi!)

Some moments to fix:
1) telephone isn't an external link, so no needs to open a new tab
2) remove body scroll when menu is opened
3) something went wrong for mobile size
<img width="609" alt="Screenshot 2023-03-13 at 19 56 08" src="https://user-images.githubusercontent.com/117587463/224788006-6f2b482e-32ef-4db1-bc23-e13122142c41.png">

2023-03-13 22:34 UTC, Vo7kov commented
https://vo7kov.github.io/layout_museum/

2023-03-14 10:42 UTC, IvanFesenko requested changes
You should fix this case
https://user-images.githubusercontent.com/61904995/224975745-b1bbd583-5730-483a-87da-cd7732f3c13a.mp4

2023-03-23 11:37 UTC, VitaliyBondarenko1982 approved these changes

2025-07-07 14:20 UTC, closed without merging