Develop
mate-academy/Museum pull request #281
Opened 2023-04-23 12:23 UTC by Faridun92

https://Faridun92.github.io/Museum/

2023-04-23 14:00 UTC, SanyaBratashchuk requested changes
1. It doesn't look like in design 
![image](https://user-images.githubusercontent.com/97547824/233843789-327d9226-14cc-4ed4-8bb6-4d0f6ff66eac.png)
2. Add hover effects for these links 
![image](https://user-images.githubusercontent.com/97547824/233844089-14d22f78-a4b4-4e50-bb51-b4f277149a49.png)
3. Add email validation
4. make email field required
5. form submit shouldn't lead to top of the page

2023-04-24 06:56 UTC, DarkMistyRoom requested changes
If you have questions, feel free to ask in the chat
- shade the background when the menu is opened
![image](https://user-images.githubusercontent.com/98764641/233919014-2658f643-1844-46c9-92a8-f5a9eab37e9c.png)
![image](https://user-images.githubusercontent.com/98764641/233919033-cb52d071-b06e-4101-8d39-e32353f64779.png)

- consider using another effect. Small scale like in the menu maybe. It looks rough without paddings
![image](https://user-images.githubusercontent.com/98764641/233919286-8a73b58d-e0a9-400b-a9d9-90a9c2520071.png)

- add a hover effect to images in this section
![image](https://user-images.githubusercontent.com/98764641/233919818-81dc6e69-cee4-49c7-95b5-ded30c061b49.png)

- there should be some padding
![image](https://user-images.githubusercontent.com/98764641/233919733-a0aee651-3372-4653-950b-62e21346564f.png)

- add email type to the form to validate the value
- check the positions of these elements
![image](https://user-images.githubusercontent.com/98764641/233920116-74b83d6b-bc0b-4254-a8c9-86e181d1748b.png)
![image](https://user-images.githubusercontent.com/98764641/233920198-74f7f930-2d77-456d-9266-08b4facb3e0a.png)

- too much empty space in the menu on the tab screen
![image](https://user-images.githubusercontent.com/98764641/233920363-91d89df6-4d9e-4a49-a616-27a36a2128e5.png)

- there should be some indent between images and pagination
![image](https://user-images.githubusercontent.com/98764641/233920497-0941e4ec-8594-40fc-8d05-258a36d01a18.png)

- the button should be 100% width, and the title should be centered
![image](https://user-images.githubusercontent.com/98764641/233920818-72cb3e51-59ef-4940-925a-0fc4d1a38aa4.png)

- there should be 15px
![image](https://user-images.githubusercontent.com/98764641/233920981-70a5ff7c-3c34-4253-a52e-d96ff92f8835.png)

- add bottom indent
![image](https://user-images.githubusercontent.com/98764641/233921076-35bd8e8d-f61a-4558-bad2-878e1a5f0d82.png)

2023-04-25 08:20 UTC, tetiana-ivanchenko requested changes
click on phone number shouldn't open new tab

2023-04-26 07:49 UTC, tetiana-ivanchenko approved these changes

2023-06-02 16:52 UTC, marina-tilniak approved these changes

2026-08-18 22:30 UTC, closed without merging