add some blocks
mate-academy/Museum pull request #332
Opened 2023-07-03 12:49 UTC by Bonum-taurus

https://Bonum-taurus.github.io/Museum

2023-07-03 13:02 UTC, mykhalenych requested changes
deploy link isn't working

2023-07-03 13:22 UTC, Bonum-taurus commented
https://Bonum-taurus.github.io/Museum/

2023-07-03 15:12 UTC, Bonum-taurus commented
https://Bonum-taurus.github.io/Museum/

2023-07-05 10:31 UTC, volodymyr-soltys97 requested changes
1. Add favicon to page
<img width="153" alt="image" src="https://github.com/mate-academy/Museum/assets/64750958/52d1226f-1061-4dce-a616-9f16ad826ef5">

2. Need to remove default styles for input after autocomplete
<img width="701" alt="image" src="https://github.com/mate-academy/Museum/assets/64750958/23497771-750f-4e79-9e10-a3d3d6001eb9">

3. Add additional styles for these elements when hovering
<img width="236" alt="image" src="https://github.com/mate-academy/Museum/assets/64750958/fc704099-1933-43e4-84f7-befdb5f2b0fe">

2023-07-05 10:31 UTC, volodymyr-soltys97 commented on src/index.html
> +                <a href="tel: +38 (044) 278-13-57" class="footer__info-tel">
Need to fix format phone only in href everywhere
```suggestion
                <a href="tel: +380442781357" class="footer__info-tel">
```

2023-07-05 12:47 UTC, Anastasiia-Svintsova requested changes
- Fix the form. Just clear it after the submission. The page shouldn't reload

https://github.com/mate-academy/Museum/assets/99403198/467f3d90-e03e-4271-9ae6-714786cba281

- Don't hardcode the content width for tablets and mobile. Just use the correct padding 
![image](https://github.com/mate-academy/Museum/assets/99403198/19cd6327-2793-4e78-b28e-e137cddc92d5)

- The image doesn't look good. Fix it 
![image](https://github.com/mate-academy/Museum/assets/99403198/140a1980-4d64-45db-b124-729a4543c29f)

- This image seems too big. Doesn't match the design 
![image](https://github.com/mate-academy/Museum/assets/99403198/b03f4deb-57b9-4ae5-a85d-9176255d2511)

2023-07-05 17:51 UTC, TarasHoliuk commented
1. The image in the header still might look a bit squeezed in some screen sizes:
![image](https://github.com/mate-academy/Museum/assets/86923089/bcc28893-4565-426e-a40a-6fd0e19db468)
It might be tricky to fix with the background image, you may try to set it as an img

not critical I guess, but at least try this way :arrow_up: 

2. Let's add a hover effect to images to make site more live

2023-07-05 17:52 UTC, TarasHoliuk requested changes
Looks good!
I've added 2 small comments to improve it a bit - check them

2023-07-06 10:48 UTC, volodymyr-soltys97 requested changes
Still not fixed
<img width="771" alt="image" src="https://github.com/mate-academy/Museum/assets/64750958/518bee02-f9b3-478d-beb0-04024271f738">

2023-07-19 14:44 UTC, closed without merging