Museum landing page
mate-academy/Museum pull request #384
Opened 2023-09-04 15:53 UTC by BodyaKutsyk

[website layout](https://www.figma.com/file/cRBCqE06cDrY3s4jX7h3iY/%D0%9D%D0%90%D0%9C%D0%A3-(Edit))
[preview link](https://bodyakutsyk.github.io/Museum/)

2023-09-04 16:11 UTC, Viktor-Kost requested changes
### GJ!

### To improve:
1. This is one button, so it shouldn't have different hover states
https://github.com/mate-academy/Museum/assets/117587463/082893b9-3bef-4ada-b7a5-e677825620cb

2. add cursor: pointer to buttons all over the page

3. remove default autocomplete styles
<img width="545" alt="Screenshot 2023-09-04 at 19 07 45" src="https://github.com/mate-academy/Museum/assets/117587463/9b866631-a11a-456c-93ee-e8f03a7bd90c">

4. page shouldn't reload after form submit

5. move logo to the center
<img width="1210" alt="Screenshot 2023-09-04 at 19 10 01" src="https://github.com/mate-academy/Museum/assets/117587463/d901b66b-f71b-499d-adb0-a3c42b6433ce">

2023-09-05 06:09 UTC, volodymyr-soltys97 requested changes
1. Add `cursor: pointer` and hover effects for all button, not only text or arrow
<img width="382" alt="image" src="https://github.com/mate-academy/Museum/assets/64750958/fdf5a79d-8354-497f-9dcc-4e31203e8eee">

2. Add the indents between the images on the slider
<img width="136" alt="image" src="https://github.com/mate-academy/Museum/assets/64750958/d2b40e1b-afc9-48e8-acbf-bdf3898c0941">

2023-09-05 07:00 UTC, volodymyr-soltys97 requested changes
Almost done!

2023-09-05 07:00 UTC, volodymyr-soltys97 commented on src/index.html
> +              <p class="footer-info-text"><span class="menu-text-bold">Вихідні:</span> понеділок, вівторок.</p>
```suggestion
              <p class="footer-info-text">
                <span class="menu-text-bold">Вихідні:</span>
                понеділок, вівторок.
              </p>
```

2023-09-05 14:50 UTC, etojeDenys approved these changes
awesome

2025-10-01 18:01 UTC, closed without merging