Museum landing
mate-academy/Museum pull request #460
Opened 2023-12-09 15:32 UTC by yurovych

https://yurovych.github.io/Museum/

2023-12-10 10:12 UTC, l4st1m0za requested changes
Great job! But some changes are required:

1) Margin here on the bigger screens looks strange. It should always be same as in figma
<img width="1544" alt="image" src="https://github.com/mate-academy/Museum/assets/67686312/2b6c0212-58f7-46e7-b251-9f803edd3a2f">

2) Menue also should have same margins as in figma even on the bigger screens
<img width="1710" alt="image" src="https://github.com/mate-academy/Museum/assets/67686312/901e2cef-8e77-4b51-a6e0-c3d16c247f8e">

3) Under the menue should be shading effect as in figma
<img width="1719" alt="image" src="https://github.com/mate-academy/Museum/assets/67686312/8f43b7db-7c7b-4e8c-affa-c54e22fb3672">

4) Photos should increase not in their container but with it. It should just get bigger as whole
<img width="715" alt="image" src="https://github.com/mate-academy/Museum/assets/67686312/62bb0ba8-477f-417c-a57e-6960077ed141">

5) Same problem with scaling in this block
<img width="1281" alt="image" src="https://github.com/mate-academy/Museum/assets/67686312/c7fd44f0-ccc1-4127-8d9f-f4ab79b3702b">

6) When I'm sending the form, I'm getting this
<img width="872" alt="image" src="https://github.com/mate-academy/Museum/assets/67686312/ef64a829-f7da-4641-92bc-721fe1ccf886">

7) Tablet layout is not as in figma
<img width="959" alt="image" src="https://github.com/mate-academy/Museum/assets/67686312/13bc008d-b028-43f4-8d69-8cbeb0e17ab9">

8) This block has problem with paddings in tablet mode
<img width="950" alt="image" src="https://github.com/mate-academy/Museum/assets/67686312/dff7389d-06cb-440f-8d22-de16186c31f0">

9) For each block in tablet mode you have different padding, but they should be same
<img width="718" alt="image" src="https://github.com/mate-academy/Museum/assets/67686312/b50d16f2-ae51-4902-82da-1b476be736e0">

10) On the phone mode, layout here is also broken
<img width="496" alt="image" src="https://github.com/mate-academy/Museum/assets/67686312/30889607-2658-4a0a-a833-f6867e1b8e1b">

11) This shuold be as in figma
<img width="447" alt="image" src="https://github.com/mate-academy/Museum/assets/67686312/7ee7f096-8a8b-4030-b6d1-e157e432e7e5">

12) That's really awesome that you have integrated a slider, but it should be styled as in figma
<img width="449" alt="image" src="https://github.com/mate-academy/Museum/assets/67686312/97bd83b8-9811-4779-ac56-08e0c5acd2c9">

2023-12-21 07:53 UTC, l4st1m0za requested changes
Very good inmrovement! See the comment, you are very close!

1) You have problems with padding in this area. If you have any questions — feel free to ask in chat
<img width="1546" alt="image" src="https://github.com/mate-academy/Museum/assets/67686312/577c763a-6c41-4069-b9ff-031af230bdf8">

2023-12-22 15:27 UTC, yurovych commented
I dont see any problems with paddings there
I also asked in chat and mentor doesn't see either
If there is some problem for real
could you clarify it please?

2023-12-22 18:52 UTC, loralevitska approved these changes
Well done)

P.S. 
Padding issue due to big screen 
![image](https://github.com/mate-academy/Museum/assets/70009205/55351b90-52c9-4bdb-9c86-2741cec3567c)
For example 1500px, looks strange due to the picture on the right fits completely to the edge of the screen, but this is the design, so it's okay for this work
![image](https://github.com/mate-academy/Museum/assets/70009205/6810ccfe-ecdb-4561-9dd4-28f528ea2b66)

2025-11-05 15:05 UTC, closed without merging